<?php

namespace ContainerXuYs0th;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N7Dgko2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n7Dgko2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n7Dgko2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AssociationController::associationAdd' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\AssociationController::associationDetails' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\AssociationController::associationList' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\AssociationController::associationListChange' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\AssociationController::associationPatch' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\AssociationController::villeDelete' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\HomeController::home' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\TownController::villeAdd' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\TownController::villeDelete' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\TownController::villeList' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\TownController::villeListChange' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\TownController::villePatch' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\UserController::userDelete' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\UserController::userList' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\UserController::villeAdd' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\UserController::villeListChange' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\UserController::villePatch' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AssociationController:associationAdd' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\AssociationController:associationDetails' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\AssociationController:associationList' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\AssociationController:associationListChange' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\AssociationController:associationPatch' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\AssociationController:villeDelete' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\HomeController:home' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\TownController:villeAdd' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\TownController:villeDelete' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\TownController:villeList' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\TownController:villeListChange' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\TownController:villePatch' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\UserController:userDelete' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\UserController:userList' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\UserController:villeAdd' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\UserController:villeListChange' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'App\\Controller\\UserController:villePatch' => ['privates', '.service_locator.v5DrvFk', 'get_ServiceLocator_V5DrvFkService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AssociationController::associationAdd' => '?',
            'App\\Controller\\AssociationController::associationDetails' => '?',
            'App\\Controller\\AssociationController::associationList' => '?',
            'App\\Controller\\AssociationController::associationListChange' => '?',
            'App\\Controller\\AssociationController::associationPatch' => '?',
            'App\\Controller\\AssociationController::villeDelete' => '?',
            'App\\Controller\\HomeController::home' => '?',
            'App\\Controller\\TownController::villeAdd' => '?',
            'App\\Controller\\TownController::villeDelete' => '?',
            'App\\Controller\\TownController::villeList' => '?',
            'App\\Controller\\TownController::villeListChange' => '?',
            'App\\Controller\\TownController::villePatch' => '?',
            'App\\Controller\\UserController::userDelete' => '?',
            'App\\Controller\\UserController::userList' => '?',
            'App\\Controller\\UserController::villeAdd' => '?',
            'App\\Controller\\UserController::villeListChange' => '?',
            'App\\Controller\\UserController::villePatch' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AssociationController:associationAdd' => '?',
            'App\\Controller\\AssociationController:associationDetails' => '?',
            'App\\Controller\\AssociationController:associationList' => '?',
            'App\\Controller\\AssociationController:associationListChange' => '?',
            'App\\Controller\\AssociationController:associationPatch' => '?',
            'App\\Controller\\AssociationController:villeDelete' => '?',
            'App\\Controller\\HomeController:home' => '?',
            'App\\Controller\\TownController:villeAdd' => '?',
            'App\\Controller\\TownController:villeDelete' => '?',
            'App\\Controller\\TownController:villeList' => '?',
            'App\\Controller\\TownController:villeListChange' => '?',
            'App\\Controller\\TownController:villePatch' => '?',
            'App\\Controller\\UserController:userDelete' => '?',
            'App\\Controller\\UserController:userList' => '?',
            'App\\Controller\\UserController:villeAdd' => '?',
            'App\\Controller\\UserController:villeListChange' => '?',
            'App\\Controller\\UserController:villePatch' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
