<?php

namespace Container1405BzX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTownControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TownController' shared autowired service.
     *
     * @return \App\Controller\TownController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/TownController.php';

        $container->services['App\\Controller\\TownController'] = $instance = new \App\Controller\TownController(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), ($container->privates['App\\Service\\FindApiService'] ?? $container->load('getFindApiServiceService')));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\TownController', $container));

        return $instance;
    }
}
