<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1405BzX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1405BzX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1405BzX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1405BzX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1405BzX\App_KernelDevDebugContainer([
    'container.build_hash' => '1405BzX',
    'container.build_id' => '1865db19',
    'container.build_time' => 1740508738,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1405BzX');
