<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXuYs0th\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXuYs0th/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXuYs0th.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXuYs0th\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXuYs0th\App_KernelDevDebugContainer([
    'container.build_hash' => 'XuYs0th',
    'container.build_id' => '4060a32d',
    'container.build_time' => 1686655984,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXuYs0th');
