<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'association_add' => [[], ['_controller' => 'App\\Controller\\AssociationController::associationAdd'], [], [['text', '/association/add']], [], [], []],
    'association_list' => [[], ['_controller' => 'App\\Controller\\AssociationController::associationList'], [], [['text', '/association/list']], [], [], []],
    'association_details' => [['id'], ['_controller' => 'App\\Controller\\AssociationController::associationDetails'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/association']], [], [], []],
    'association_patch' => [['id'], ['_controller' => 'App\\Controller\\AssociationController::associationPatch'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/association/patch']], [], [], []],
    'association_delete' => [['id'], ['_controller' => 'App\\Controller\\AssociationController::villeDelete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/association/delete']], [], [], []],
    'association_list_change' => [[], ['_controller' => 'App\\Controller\\AssociationController::associationListChange'], [], [['text', '/association/list/change']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::home'], [], [['text', '/home']], [], [], []],
    'ville_list' => [[], ['_controller' => 'App\\Controller\\TownController::villeList'], [], [['text', '/ville/list']], [], [], []],
    'ville_patch' => [['id'], ['_controller' => 'App\\Controller\\TownController::villePatch'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/ville/patch']], [], [], []],
    'ville_delete' => [['id'], ['_controller' => 'App\\Controller\\TownController::villeDelete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/ville/delete']], [], [], []],
    'user_list' => [[], ['_controller' => 'App\\Controller\\UserController::userList'], [], [['text', '/user/list']], [], [], []],
    'ville_list_change' => [[], ['_controller' => 'App\\Controller\\UserController::villeListChange'], [], [['text', '/ville/list/change']], [], [], []],
    'ville_add' => [[], ['_controller' => 'App\\Controller\\UserController::villeAdd'], [], [['text', '/ville/add']], [], [], []],
    'user_patch' => [['id'], ['_controller' => 'App\\Controller\\UserController::villePatch'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user/patch']], [], [], []],
    'user_delete' => [['id'], ['_controller' => 'App\\Controller\\UserController::userDelete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user/delete']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
];
